version: 1.2.4

cache: true

interface:
  privacyPolicy:
    externalUrl: 'https://librechat.ai/privacy-policy'
    openNewTab: true
  termsOfService:
    externalUrl: 'https://librechat.ai/tos'
    openNewTab: true

registration:
  socialLogins:
    - "google"

mcpServers:
  nanobanana:
    command: uvx
    args:
      - nanobanana-mcp-server@latest
    env:
      GEMINI_API_KEY: "${GOOGLE_KEY}"
  filesystem:
    command: npx
    args:
      - -y
      - "@modelcontextprotocol/server-filesystem"
      - /home/node/nanobanana-images/
      - /app/client/public/images/

endpoints:
    - name: 'Adapter'
      apiKey: '${PORTKEY_API_KEY}'
      baseURL: '${ADAPTER_URL}'
      headers:
        x-portkey-api-key: '${PORTKEY_API_KEY}'
        x-portkey-config: '${PORTKEY_CONFIG_ID}'
        x-portkey-metadata: '{"_user":"{{LIBRECHAT_USER_EMAIL}}"}'
      models:
        default:
          - gemini-2.5-flash-lite
          - general-purpose
        fetch: true
      modelDisplayLabel: 'Models'
      titleConvo: true
      titleModel: 'current_model'
      summarize: false
      summaryModel: 'current_model'
      forcePrompt: false
      iconURL: https://cdn-icons-png.flaticon.com/512/13819/13819669.png
      addParams:
        web_search: true

webSearch:
  jinaApiKey: '${JINA_API_KEY}'  # Your Jina API key
  serperApiKey: '${SERPER_API_KEY}'