version: 1.2.4

cache: true

interface:
  privacyPolicy:
    externalUrl: 'https://librechat.ai/privacy-policy'
    openNewTab: true
  termsOfService:
    externalUrl: 'https://librechat.ai/tos'
    openNewTab: true

registration:
  socialLogins:
    - "google"

mcpServers:
  nanobanana:
    command: uvx
    args:
      - nanobanana-mcp-server@latest
    env:
      GEMINI_API_KEY: "${GOOGLE_KEY}"